Repository echo1241/echo, pull requests merged in 2024-08, with the labels that each got.

#43 [Feat] 토큰 재발급
  build.gradle
  docker-compose.yml
  http/auth.http
  http/user.http
  src/main/java/com/echo/echo/common/exception/CustomException.java
  src/main/java/com/echo/echo/common/exception/codes/CommonErrorCode.java
  src/main/java/com/echo/echo/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/echo/echo/common/redis/RedisService.java
  src/main/java/com/echo/echo/config/RedisConfig.java
  src/main/java/com/echo/echo/domain/auth/AuthController.java
  src/main/java/com/echo/echo/domain/auth/AuthFacade.java
  src/main/java/com/echo/echo/domain/auth/AuthService.java
  src/main/java/com/echo/echo/domain/auth/dto/TokenRequestDto.java
  src/main/java/com/echo/echo/domain/auth/dto/TokenResponseDto.java
  src/main/java/com/echo/echo/domain/auth/error/AuthErrorCode.java
  src/main/java/com/echo/echo/domain/user/UserFacade.java
  src/main/java/com/echo/echo/domain/user/UserService.java
  src/main/java/com/echo/echo/domain/user/entity/RefreshToken.java
  src/main/java/com/echo/echo/domain/user/entity/User.java
  src/main/java/com/echo/echo/security/jwt/JwtProvider.java
  src/main/resources/application.properties
Labels: feat

#49 [Feat] Video Call 구현
  build.gradle
  src/main/java/com/echo/echo/config/WebSocketConfig.java
  src/main/java/com/echo/echo/domain/video/VideoHandler.java
  src/main/java/com/echo/echo/domain/voice/SignalHandler.java
  src/main/java/com/echo/echo/security/config/SecurityConfig.java
  src/main/resources/templates/video/index.html
  src/main/resources/templates/voice/index.html
Labels: feat

#46 [Feat] friend CRUD
  http/friend.http
  src/main/java/com/echo/echo/domain/friend/FriendController.java
  src/main/java/com/echo/echo/domain/friend/FriendFacade.java
  src/main/java/com/echo/echo/domain/friend/FriendService.java
  src/main/java/com/echo/echo/domain/friend/dto/FriendshipResponseDto.java
  src/main/java/com/echo/echo/domain/friend/dto/RequestFriendResponseDto.java
  src/main/java/com/echo/echo/domain/friend/entity/Friendship.java
  src/main/java/com/echo/echo/domain/friend/entity/RequestFriend.java
  src/main/java/com/echo/echo/domain/friend/error/FriendErrorCode.java
  src/main/java/com/echo/echo/domain/friend/error/FriendSuccessCode.java
  src/main/java/com/echo/echo/domain/friend/repository/FriendshipRepository.java
  src/main/java/com/echo/echo/domain/friend/repository/RequestFriendRepository.java
  src/main/java/com/echo/echo/security/principal/UserPrincipal.java
  src/main/resources/schema.sql
Labels: feat, refactor

#56 [feat fix] 사용자 및 스페이스 리스트 조회 기능
  http/space.http
  src/main/java/com/echo/echo/domain/channel/ChannelFacade.java
  src/main/java/com/echo/echo/domain/channel/ChannelService.java
  src/main/java/com/echo/echo/domain/space/SpaceController.java
  src/main/java/com/echo/echo/domain/space/SpaceFacade.java
  src/main/java/com/echo/echo/domain/space/SpaceService.java
  src/main/java/com/echo/echo/domain/space/error/SpaceErrorCode.java
  src/main/java/com/echo/echo/domain/space/repository/SpaceMemberRepository.java
Labels: fix, feat

#74 [Feat] Ci/Cd 파이프라인 설정
  .github/workflows/CiCd.yml
  .github/workflows/cd-dev.yml
  .github/workflows/ci-dev.yml
Labels: feat, refactor, setup

#79 [Feat] Typing Indicators 구현
  src/main/java/com/echo/echo/common/redis/RedisConst.java
  src/main/java/com/echo/echo/common/redis/RedisListener.java
  src/main/java/com/echo/echo/domain/text/TextService.java
  src/main/java/com/echo/echo/domain/text/controller/TextWebSocketHandler.java
  src/main/java/com/echo/echo/domain/text/dto/TypingRequest.java
  src/main/java/com/echo/echo/domain/text/dto/TypingResponse.java
Labels: feat

#88 [Feat] chatroom member limit
  http/channel.http
  src/main/java/com/echo/echo/common/aop/SseAspect.java
  src/main/java/com/echo/echo/config/WebSocketConfig.java
  src/main/java/com/echo/echo/domain/channel/ChannelService.java
  src/main/java/com/echo/echo/domain/channel/dto/ChannelRequestDto.java
  src/main/java/com/echo/echo/domain/channel/dto/ChannelResponseDto.java
  src/main/java/com/echo/echo/domain/channel/entity/Channel.java
  src/main/java/com/echo/echo/domain/channel/error/ChannelErrorCode.java
  src/main/java/com/echo/echo/domain/text/controller/TextWebSocketHandler.java
  src/main/java/com/echo/echo/domain/video/VideoHandler.java
  src/main/resources/schema.sql
Labels: feat

#90 [Fix] VideoHandler.java에 ping 반영
  src/main/java/com/echo/echo/domain/video/VideoHandler.java
Labels: fix

#94 [feat] Text 수정, 삭제 기능 추가
  http/text.http
  src/main/java/com/echo/echo/common/TimeStamp.java
  src/main/java/com/echo/echo/config/MongoDBConfig.java
  src/main/java/com/echo/echo/domain/TextFacade.java
  src/main/java/com/echo/echo/domain/text/TextFacade.java
  src/main/java/com/echo/echo/domain/text/TextService.java
  src/main/java/com/echo/echo/domain/text/controller/TextController.java
  src/main/java/com/echo/echo/domain/text/controller/TextWebSocketHandler.java
  src/main/java/com/echo/echo/domain/text/dto/TextRequest.java
  src/main/java/com/echo/echo/domain/text/dto/TextResponse.java
  src/main/java/com/echo/echo/domain/text/entity/Text.java
  src/main/java/com/echo/echo/domain/text/error/TextErrorCode.java
Labels: 🔥feat

#101 [Refactor] ErrorCode 및 SuccessCode의 규칙 및 형식 통일
  src/main/java/com/echo/echo/common/exception/CommonReason.java
  src/main/java/com/echo/echo/common/exception/codes/CommonErrorCode.java
  src/main/java/com/echo/echo/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/echo/echo/common/s3/error/S3ErrorCode.java
  src/main/java/com/echo/echo/domain/auth/error/AuthErrorCode.java
  src/main/java/com/echo/echo/domain/channel/error/ChannelErrorCode.java
  src/main/java/com/echo/echo/domain/channel/error/ChannelSuccessCode.java
  src/main/java/com/echo/echo/domain/friend/error/FriendErrorCode.java
  src/main/java/com/echo/echo/domain/friend/error/FriendSuccessCode.java
  src/main/java/com/echo/echo/domain/space/error/SpaceErrorCode.java
  src/main/java/com/echo/echo/domain/space/error/SpaceSuccessCode.java
  src/main/java/com/echo/echo/domain/text/error/TextErrorCode.java
  src/main/java/com/echo/echo/domain/thread/error/ThreadErrorCode.java
  src/main/java/com/echo/echo/domain/user/error/UserErrorCode.java
  src/main/java/com/echo/echo/domain/user/error/UserSuccessCode.java
Labels: ♻️ refactor
